"""
Author: Hanan Abdulwahab Siala
University: King's College London
Date: 2020-10-05

Description:
    This program post-processes OCL specifications generated by the LLM4Models LLM from both Java and Python programs.
"""
# ------------------------------------------------------------------------------
import re
# ------------------------------------------------------------------------------
def CleanOCL(lines):
   text = '\n'.join(lines)
   while True:
      oldText = text
      text = re.sub(r';\s*;', ';', text)           # ";;" -> ";"
      text = re.sub(r';\s*else', 'else', text)     # "; else" -> "else"
      text = re.sub(r';\s*skip', '', text)         # "; skip" -> remove
      text = re.sub(r'skip\s*;', '', text)         # "skip ;" -> remove
      text = re.sub(r'\(\s*skip\s*;', '(', text)   # "( skip ;" -> "("
      text = re.sub(r'skip\s*;\s*\(', '(', text)   # "skip ; (" -> "("
      text = re.sub(r';\s*\)', ')', text)          # "; )" -> ")"

      text = re.sub(r'[ \t]+', ' ', text)          # clean extra spaces  
      text = re.sub(r'\n\s+', '\n', text)
      if text == oldText:
         break
   return text.strip()
# ------------------------------------------------------------------------------
def ProcessFile(input_file, output_file):
   with open(input_file, 'r') as f:
      lines = f.readlines()
   cleaned = CleanOCL(lines)
   with open(output_file, 'w') as f:
      f.write(cleaned)
# ------------------------------------------------------------------------------
Source_file=####
Destination_file=####
ProcessFile(Source_file, Destination_file)
# ------------------------------------------------------------------------------
