"""
Author: Hanan Abdulwahab Siala
University: King's College London
Date: 2020-10-05

Description:
    This program post-processes UML class diagrams generated by the LLM4Models LLM from both Java and Python programs.
"""
# ------------------------------------------------------------------------------
import json
import os
import re
import ast
# ------------------------------------------------------------------------------
Language="Java"
#Language="Python"
Directory = ####       
File="LLM4Models.txt"
# ------------------------------------------------------------------------------
def DealingWithSlashesInPython(text):
   result = re.sub(r"= *'([^']*)'", r'=\\\"\1\\\"', text)

   result1 = re.sub(
      r"\('([^']*?)'\)",
      lambda m: r'(\\"' + m.group(1) + r'\\")',  
      result
   )

   result2 = re.sub(
      r"\(\\'([^']*?)\\'\)",
      lambda m: r'(\\"' + m.group(1) + r'\\")',  
      result1
   )

   return result2 
# ------------------------------------------------------------------------------
def IsTypeReferencingClass(typeprint, ClassNames):
   for ClassName in ClassNames:
      if ClassName in typeprint:
         return True
   return False
# ------------------------------------------------------------------------------
def PostprocessJSONFile(UML):
   ClassNames = {cls["name"] for cls in UML}
   for cls in UML:
      cls["variables"] = [
         var for var in cls.get("variables", [])
         if not IsTypeReferencingClass(var.get("typeprint", ""), ClassNames)
      ]
   return UML 
# ------------------------------------------------------------------------------
def ReplaceTypeWithTypeprint(obj):
   if isinstance(obj, dict):
      new_obj = {}
      for key, value in obj.items():
         new_key = "typeprint" if key in ["type", "typePrint"] else key
         new_obj[new_key] = ReplaceTypeWithTypeprint(value)
      return new_obj
   elif isinstance(obj, list):
      return [ReplaceTypeWithTypeprint(item) for item in obj]
   else:
      return obj
# ------------------------------------------------------------------------------
def SplitJSON(Data, Root):
   Data = json.loads(Data)
   Data = ReplaceTypeWithTypeprint(Data)
   classes = Data.get("classes", [])
    
   classes=PostprocessJSONFile(classes) 
   relationships = Data.get("relationships", [])
   with open(os.path.join(Root, "Test1.UML"), "w", encoding="utf-8") as UMLFile:
      json.dump(classes, UMLFile, indent=4)
   with open(os.path.join(Root, "Test1.REL"), "w", encoding="utf-8") as RELFile:
      json.dump(relationships, RELFile, indent=4)     
# ------------------------------------------------------------------------------
File= os.path.join(Directory, File)
print(File)
with open(File, 'r', encoding='utf-8') as file:
   Output = file.read()
   try:
      if Language=="Python":
         Output = DealingWithSlashesInPython(Output)
         Output = Output.replace("\\'", '\\"') 
         Output = re.sub(r'\bf"', '"', Output) 
      DataDict = ast.literal_eval(Output)  
      if 'Classes' in DataDict:
         DataDict['classes'] = DataDict.pop('Classes')
      if 'Relationships' in DataDict:
         DataDict['relationships'] = DataDict.pop('Relationships')
      if isinstance(DataDict.get('classes'), str):
         DataDict['classes'] = json.loads(DataDict['classes'])
      if isinstance(DataDict.get('relationships'), str):
         DataDict['relationships'] = json.loads(DataDict['relationships'])
      OutputCleaned = json.dumps(DataDict, indent=4)
      SplitJSON(OutputCleaned, Directory)
   except Exception as e:
      print(f"Failed to parse {File}: {e}")
# ------------------------------------------------------------------------------

