"""
Author: Hanan Abdulwahab Siala
University: King's College London
Date: 17-02-2026

Description:
    This program post-processes OCL specifications generated by the LLM4Models LLM from both Java and Python programs.
"""
# ------------------------------------------------------------------------------
import re
# ------------------------------------------------------------------------------
def CleanOCL(lines):
   text = "".join(lines)
   while True:
      oldText = text
      text = re.sub(r';[ \t]*;', ';', text)            # ";;" -> ";"
      text = re.sub(r';[ \t]*else', 'else', text)      # "; else" -> "else"
      text = re.sub(r';[ \t]*skip', '', text)          # "; skip" -> remove
      text = re.sub(r'skip[ \t]*;', '', text)          # "skip ;" -> remove
      text = re.sub(r'\([ \t]*skip[ \t]*;', '(', text) # "( skip ;" -> "("
      text = re.sub(r'skip[ \t]*;[ \t]*\(', '(', text) # "skip ; (" -> "("
      text = re.sub(r';[ \t]*\)', ')', text)           # "; )" -> ")" 
      if text == oldText:
         break
   return text.strip()   
# ------------------------------------------------------------------------------
def ProcessFile(input_file, output_file):
   with open(input_file, 'r') as f:
      lines = f.readlines()
   cleaned = CleanOCL(lines)
   with open(output_file, 'w') as f:
      f.write(cleaned)
# ------------------------------------------------------------------------------
Source_file=####
Destination_file=####
ProcessFile(Source_file, Destination_file)
# ------------------------------------------------------------------------------
